# Generated by Django 4.1.5 on 2023-01-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geo', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('people_name_in_foto', models.CharField(max_length=250)),
                ('foto_im', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
